### ISSUE TITLE
Managers' Search function in Perform a payout section can't find yeeted members

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#56]
https://www.rockwelltransport.com/home/dashboard/payout

Please allow the search function in the managers' Perform a payout tool to find yeeted members, not just active ones.

**Comment by rhit-corridg** [comment]
This is a bit of a weird request. Why would you want to payout a yeeted member? Shouldn't the workflow be that you have to rehire them? 

Keep in mind, if we do this, it'll be searching through thousands of members. It'll significantly slow down loading the page and managers won't be able to be as general in their searches because more results will pop up.

**Comment by rhit-corridg** [comment]
Stale
